from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from crm import get_all_leads, Session, Lead, ChatLog
from datetime import datetime, timedelta
import os

def generate_leads_pdf(client_id: str, date: datetime = None) -> str:
    if not date:
        date = datetime.utcnow()

    # filter leads from that date
    db    = Session()
    start = date.replace(hour=0, minute=0, second=0, microsecond=0)
    end   = start + timedelta(days=1)
    leads = db.query(Lead).filter(
        Lead.channel != None,
        Lead.created >= start,
        Lead.created < end
    ).order_by(Lead.created.desc()).all()
    db.close()

    # build PDF
    os.makedirs("exports", exist_ok=True)
    filename = f"exports/{client_id}_{date.strftime('%Y-%m-%d')}_leads.pdf"
    doc      = SimpleDocTemplate(filename, pagesize=A4,
                                  leftMargin=20*mm, rightMargin=20*mm,
                                  topMargin=20*mm, bottomMargin=20*mm)
    styles   = getSampleStyleSheet()
    story    = []

    # title
    title_style = ParagraphStyle('title', fontSize=18, fontName='Helvetica-Bold',
                                  spaceAfter=4, textColor=colors.HexColor('#0ACF83'))
    sub_style   = ParagraphStyle('sub', fontSize=11, fontName='Helvetica',
                                  textColor=colors.gray, spaceAfter=16)

    story.append(Paragraph("Zeno — Daily Lead Report", title_style))
    story.append(Paragraph(f"{client_id.replace('_', ' ').title()}  |  {date.strftime('%d %B %Y')}", sub_style))
    story.append(Spacer(1, 6))

    if not leads:
        story.append(Paragraph("No leads captured on this date.", styles['Normal']))
    else:
        # summary line
        story.append(Paragraph(f"Total leads: <b>{len(leads)}</b>", styles['Normal']))
        story.append(Spacer(1, 10))

        # table
        table_data = [["#", "Name", "Phone", "Email", "Channel", "Time"]]
        for i, l in enumerate(leads, 1):
            table_data.append([
                str(i),
                l.name  or "—",
                l.phone or "—",
                l.email or "—",
                l.channel or "—",
                l.created.strftime("%I:%M %p")
            ])

        t = Table(table_data, colWidths=[10*mm, 40*mm, 35*mm, 55*mm, 25*mm, 20*mm])
        t.setStyle(TableStyle([
            ('BACKGROUND',  (0,0), (-1,0),  colors.HexColor('#0ACF83')),
            ('TEXTCOLOR',   (0,0), (-1,0),  colors.white),
            ('FONTNAME',    (0,0), (-1,0),  'Helvetica-Bold'),
            ('FONTSIZE',    (0,0), (-1,0),  10),
            ('FONTSIZE',    (0,1), (-1,-1), 9),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor('#F5F5F5')]),
            ('GRID',        (0,0), (-1,-1), 0.3, colors.HexColor('#DDDDDD')),
            ('ROWHEIGHT',   (0,0), (-1,-1), 18),
            ('VALIGN',      (0,0), (-1,-1), 'MIDDLE'),
            ('LEFTPADDING', (0,0), (-1,-1), 6),
        ]))
        story.append(t)

    story.append(Spacer(1, 20))
    story.append(Paragraph(
        f"Generated by Zeno on {datetime.utcnow().strftime('%d %b %Y, %I:%M %p')} UTC",
        ParagraphStyle('footer', fontSize=8, textColor=colors.gray)
    ))

    doc.build(story)
    return filename